///////////////////////////////////////////////////////////////////////////////
// This header file was generated by the SettingsParser
// at 9/20/2016 10:03:32 AM
#ifndef __CFGCONSTANTS_h
#define __CFGCONSTANTS_h

// Enum definitions
#define cfgENUM_UF_UNUSED 0
#define cfgENUM_UF_ESP8266 1
#define cfgENUM_UF_RADIO 2
#define cfgENUM_UF_GPSNMEA 3
#define cfgENUM_UF_GPSUBX 4

#define cfgENUM_ADCL_VBAT 0
#define cfgENUM_ADCL_ADC1 1
#define cfgENUM_ADCL_ADC2 2
#define cfgENUM_ADCL_ADC3 3

// Value definitions
#define cfgVAL_SYS_UID 0
#define cfgVAL_SYS_NAME 1
#define cfgVAL_WIFI_SSID 2
#define cfgVAL_WIFI_PWD 3
#define cfgVAL_WIFI_LOCAL 4
#define cfgVAL_WIFI_REMOTE 5
#define cfgVAL_UART_U1F 6
#define cfgVAL_UART_U1B 7
#define cfgVAL_UART_U2F 8
#define cfgVAL_UART_U2B 9
#define cfgVAL_UART_U3F 10
#define cfgVAL_UART_U3B 11
#define cfgVAL_UART_U4F 12
#define cfgVAL_UART_U4B 13
#define cfgVAL_ENERGY_VBAT 14
#define cfgVAL_ENERGY_VBAT_OFFSET 15
#define cfgVAL_ENERGY_VBAT_SCALE 16
#define cfgVAL_ENERGY_VBAT_MIN 17
#define cfgVAL_ENERGY_VBAT_MAX 18
#define cfgVAL_ENERGY_IBAT 19
#define cfgVAL_ENERGY_IBAT_OFFSET 20
#define cfgVAL_ENERGY_IBAT_SCALE 21

// Configuration constants
#define cfg_XML_DATA_FILE_LENGTH 829
#define cfg_VALUE_INFO_DATA_FILE_LENGTH 88
#define cfg_VALUE_DATA_FILE_LENGTH 157
#define cfg_VALUE_COUNT 22

#endif
