///////////////////////////////////////////////////////////////////////////////
// This header file was generated by the ROXParser
// at 4/13/2017 2:01:09 AM

#ifndef __ROXPACKETS_H
#define __ROXPACKETS_H

/*****************************************************************************/
/* Packet types                                                              */
/*****************************************************************************/
#define roxPT_UltrasonicDistance 1
#define roxPT_AirTemperature 2

/*****************************************************************************/
/* Packets                                                                   */
/*****************************************************************************/

///////////////////////////////////////////////////////////////////////////////
// UltrasonicDistance
typedef struct
{
  comPacketHeader Header;

  uint16_t Distance1;
  uint16_t Distance2;
  uint16_t Distance3;
  uint16_t Distance4;
} roxUltrasonicDistance;

///////////////////////////////////////////////////////////////////////////////
// AirTemperature
typedef struct
{
  comPacketHeader Header;

  uint16_t TemperatureADC;
  uint16_t Temperature;
} roxAirTemperature;


#endif

