///////////////////////////////////////////////////////////////////////////////
// This header file was generated by the SettingsParser
// at 9/20/2016 10:03:32 AM
#ifndef __CFGCONSTANTS_h
#define __CFGCONSTANTS_h

#define cfgVAL_WIFI_LOCAL 1
#define cfgVAL_WIFI_REMOTE 2

#endif
