///////////////////////////////////////////////////////////////////////////////
// This header file was generated by the SettingsParser
// at 4/21/2015 2:07:06 PM
#ifndef __SETTING_H
#define __SETTING_H

#define cfgWIFITELEMETRY_SSID 0
#define cfgWIFITELEMETRY_PASSWORD 16
#define cfgWIFITELEMETRY_PORT 48

#define cfgSETTINGS_XML_FILE_LENGTH 154
#define cfgSETTINGS_BINARY_FILE_LENGTH 52

#endif
